[package]
name = "os"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]

[dependencies.std]
path = "../rust-libs/std"

[dependencies.bitflags]
path = "../rust-libs/bitflags"

[dependencies.marble]
path = "../libs/marble"
