[package]
name = "rustos_experiment"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]

[lib]
name = "rustos_experiment"
crate-type = ["staticlib"]

[dependencies.unimplemented_functions]
path = "lib/unimplemented_functions"

[dependencies]
rlibc = "*"